### ISSUE TITLE
Hanging at "getting last page"

### ISSUE THREAD

**Issue by Dowscar** [pipoket/booru-grabber#2]
Just started the other day, but it'll sit like this for hours if I leave it alone, seemingly regardless of tags.
![untitled](https://github-cloud.s3.amazonaws.com/assets/15183843/10565344/449405a6-759c-11e5-9770-e9ac07f68c78.png)

**Comment by pipoket** [comment]
Okay, Gelbooru is apparantly blocking using their API for a moment. Every single API call simply returns text 'Our API is being abused at the moment and is disabled', bummer.

I've been thinking that rather than using such problemetic API, just go with the old-way of gathering HTML page and parsing image URL out of it. This might take some time and cumbersome, but will be much more guaranteed to work.

**Comment by pipoket** [comment]
There ya go. Workaround for API blockage.

Try with release 0.2.2 :)

![booru-grabber-issue-2](https://cloud.githubusercontent.com/assets/653592/10603233/e2407f16-7757-11e5-9e35-eab79ceba9f6.JPG)
