### ISSUE TITLE
Non-ASCII character on Grabber path causes exception while loading configuration from file

### ISSUE THREAD

**Issue by Litoba** [pipoket/booru-grabber#3]
![problem](https://cloud.githubusercontent.com/assets/15212715/10606132/8ec41852-776b-11e5-96a5-bf25e44d25d5.jpg)

I'm sorry.
I can't speak English well.
I don't know programming.
I wanna know about this problem by booru-grabber-0.2.2-win32.

**Comment by pipoket** [comment]
I think this happens because there is non ASCII character(= non-English character) where you have extracted Grabber into. Could you try following?
1. Move Grabber to the path where only English characters are used
   - As of now, paths with non-English character can cause problem. For example:
     - Bad: "C:\Documents And Settings\User\바탕화면\"  ('바탕화면' can cause problem)
     - Good: "C:\Downloads\English\Only"
2. After moving Grabber, delete 'config.ini' file within Grabber directory to reset the whole configuration

Anyway, this is a bug on Grabber side and I'll fix it whenever possible. Until then, please make sure to place Grabber in the path with only ASCII characters.

Thanks for the bug report!

**Comment by pipoket** [comment]
Fixed by 0988197 (Python 3.x binary string yay!)
